### ISSUE TITLE
ControllerFactory shouldn't use static path for loading

### ISSUE THREAD

**Issue by hekike** [emartech/boar-stack-boilerplate#2]
```
ControllerFactory.load = function(pathToAction) {
  return require(path.join(appRoot + '/controllers', pathToAction));
};
```

It's not gonna fly. If the `controllers/` isn't take a place in the project's root.

**Comment by drawain** [comment]
Our projects only usable after building it - and the build always moves the controllers to the root path. The concept we started to use in our services is that we move most of the business logic to external modules/components and the application itself mostly contains routing and controllers. This way we force ourselves to keep our services relatively small.

**Comment by hekike** [comment]
Thanks!
